<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsAspireSharedProject>true</IsAspireSharedProject>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="AspNetCore.HealthChecks.Uris" Version="9.0.0" />
    <PackageReference Include="DotNext" Version="5.21.0" />
    <PackageReference Include="Grpc.AspNetCore.HealthChecks" Version="2.71.0" />
    <PackageReference Include="Grpc.HealthCheck" Version="2.71.0" />
    <PackageReference Include="Grpc.Net.ClientFactory" Version="2.71.0" />

    <PackageReference Include="Microsoft.Extensions.Http.Resilience" Version="9.4.0" />
    <PackageReference Include="Microsoft.Extensions.ServiceDiscovery" Version="9.2.1" />
    <PackageReference Include="Nito.AsyncEx.Context" Version="5.1.2" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.12.0" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.12.0" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.11.1" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.11.1" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Runtime" Version="1.11.1" />
    <PackageReference Include="Stripe.net" Version="48.0.2" />
    <PackageReference Include="VaultSharp" Version="1.17.5.1" />
    <PackageReference Include="VaultSharp.Extensions.Configuration" Version="1.1.2" />
  </ItemGroup>

</Project>
